name: Build and Deploy
on:
  push:
    branches: ['main']
  schedule:
    branches: ['main']
    - cron: "0 0 * * 0"
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: build
        run: |
          make -C docs/ html

      - name: deploy
        if: steps.build.outcome == 'success'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          branch: main
          git-config-name: Stefan Appelhoff
          git-config-email: stefan.appelhoff@mailbox.org
          commit-message: updates [skip ci]
          single-commit: true
